# Parameters for the example pipeline
# Split ratio between testing data and training data
#test_size: 0.2

# Parameter to train a xgb classifier
#random_state: 42
max_depth: [3, 5, 7]
learning_rate: [0.001, 0.01, 0.1, 0.2, 0.3]
n_estimators: [50, 100, 200]
#cv: 5
#scoring: neg_mean_squared_error
#verbosity: 0
