name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9  # Adjust this to your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt  

      - name: Deploy Streamlit app
        run: |
          mkdir -p ~/.streamlit
          echo "\
          [server]\n\
          port = $PORT\n\
          enableCORS = false\n\
          " > ~/.streamlit/config.toml
          streamlit run app.py &>/dev/null &  # Replace with the path to your Streamlit app file
